### ISSUE TITLE
Orders endpoint unit tests

### ISSUE THREAD

**Issue by josephh** [MinhazH99/orders101#6]
# Test this with spring boot test runner   
* https://www.baeldung.com/spring-boot-testing
* https://docs.spring.io/spring-boot/docs/1.5.2.RELEASE/reference/html/boot-features-testing.html
## test controller endpoints with a combination of mocking the database (or dao interfaces) and running h2 in memory as part of the test.     
1. Happy path - Use expectations (mockito and hamcrest) to  confirm application behaviour.  E.g. is the dao called the right number of times with the right arguments?
2. Unhappy path - pass in an invalid order when creating a new order.  Confirm status response code and errors details 
3. Unhappy path - pass in a non existing order id.  Confirm status response code.

**Comment by MinhazH99** [comment]
### Happy Path

1. Assert the response code is as expected
2. Use the JSON in the reponse to create an in-memory order
3. Assert that the values within the order are as expected

### Unhappy Path
1. Checking the response code (check if response code is 404)
2. Check the details within the error
